INSERT INTO  question(libelle,indice) Values('Planter, entretenir des arbres, des arbustes, des fleurs ou cultiver le sol','Realiste'),
('Faire de la couture','Réaliste'),
('Effectuer des réparations électriques ou électroniques.','Realiste'),
('Réparer des automobiles.','Réaliste'),
('Fabriquer des objets avec du bois.','Realiste'),
('Conduire un camion ou un tracteur.','Realiste'),
('Faire des déménagements.','Realiste'),
('Entretenir ou réparer de la plomberie ou des systèmes de ventilation.','Realiste'),
('Travailler avec des animaux et en prendre soin.','Realiste'),
('Travailler à l’extérieur (exposer à la pluie, au soleil, au froid).','Realiste'),
('Travailler avec de la machinerie.','Realiste'),
('Préparer des repas, des banquets.','Realiste'),
('Travailler avec des outils tels que tournevis, ciseaux, pince, etc.','Realiste'),
('Effectuer des travaux de peinture.','Realiste'),
('Suivre un cours de dessin mécanique.','Realiste'),
('Lire des revues scientifiques ou spécialisées','Investigateur'),
(' Faire des expériences sur le comportement des animaux.','Investigateur'),
('Effectuer des analyses en laboratoire.','Investigateur'),
('Suivre des cours de sciences.','Investigateur'),
('Établir un diagnostic de maladie chez des patients.','Investigateur'),
('Expérimenter de nouvelles cultures végétales.','investigateur'),
('Créer une nouvelle source d’énergie.','Investigateur'),
(' Concevoir un barrage électrique, un pont, une autoroute, etc.','Investigateur'),
(' Résoudre des problèmes mathématiques.','Investigateur'),
(' Faire des recherches scientifiques pour satisfaire ma curiosité.','Investigateur'),
('Produire un rapport sur l’évolution économique d’une région.','Investigateur'),
('Concevoir un plan de reboisement.','Investigateur'),
('Planifier des soins ou des traitements à donner à des patients.','Investigateur'),
('Faire des recherches sur les civilisations anciennes.','Investigateur'),
('Faire de la programmation informatique.','Investigateur'),
(' Écrire des romans, des articles de journaux.','Artiste'),
('Dessiner des meubles, des plans de maison, des décors, etc.','Artiste'),
(' Interpréter ou mettre en scène une pièce de théâtre','Artiste'),
('Jouer dans un orchestre','Artiste'),
('Créer des pièces d’artisanat.','Artiste'),
('Imaginer de nouvelles façons de faire les choses.','Artiste'),
('Embellir l’environnement.','Artiste'),
('Créer une nouvelle coupe de cheveux ou de nouveau vêtement.','Artiste'),
('Faire de la photographie publicitaire ou artistique.','Artiste'),
('Concevoir et réaliser des arrangements de fleurs.','Artiste'),
(' Imaginer une bande dessinée.','Artiste'),
(' Peindre des tableaux pour une exposition.','Artiste'),
('Décorer des vitrines de magasins.','Artiste'),
(' Écrire des critiques de pièces de théâtre, de films, de livres, etc.','Artiste'),
(' Apprendre des langues.','Artiste'),
('S’engager dans des organismes sociaux ou communautaires.','Social'),
('Rencontrer des gens pour les aider à résoudre leurs problèmes personnels.','Social'),
('Travailler dans une garderie d’enfants.','Social'),
('Enseigner aux enfants, aux adolescents, aux adultes.','Social'),
('Aider les gens à prendre conscience de leurs possibilités.','Social'),
('Animer un groupe.','Social'),
('Agir comme hôte / hôtesse lors d’un congrès.','Social'),
('Tenir un kiosque d’information.','Social'),
('Offrir un service d’aide téléphonique.','Social'),
('Consulter les gens sur leurs besoins (sondage, enquête, etc.).','Social'),
('S’occuper des personnes handicapées physiquement.','Social'),
('Soigner un malade.','Social'),
('Aider les délinquants à se réhabiliter.','Social'),
('Organiser des loisirs.','Social'),
(' Échanger des idées avec d’autres personnes.','Social'),
(' Vendre un produit ou une idée.','Entrepreneur'),
(' Mettre sur pied son propre commerce.','Entrepreneur'),
('Donner des conférences.','Entrepreneur'),
('Acheter pour le compte d’un grand magasin.','Entrepreneur'),
('Marchander.','Entrepreneur'),
(' Diriger du personnel.','Entrepreneur'),
('Défendre une cause.','Entrepreneur'),
('Faire de la sélection de candidats.','Entrepreneur'),
('S’engager à fond dans des activités sociales au travail ou dans son quartier.','Entrepreneur'),
('Diriger une entreprise financière.','Entrepreneur'),
('Lancer un nouveau produit.','Entrepreneur'),
('Fonder un club de consommateurs, une association de protection de l’environnement, une activité de récupération de papier.','Entrepreneur'),
('Gérer un projet spécial.','Entrepreneur'),
('Faire de la politique (municipal, scolaire, provincial)','Entrepreneur'),
('Lancer un concours de promotion, une campagne de publicité.','Entrepreneur'),
(' Établir des comptes-rendus des dépenses.','Conventionnel'),
('Préparer des procès verbaux de réunions.','Conventionnel'),
('Tenir une caisse dans un établissement commercial ou financier.','Conventionnel'),
('Faire un inventaire et passer des commandes.','Conventionnel'),
(' Manipuler un appareil à traitement de textes','Conventionnel'),
('Maintenir un système de classement (archive, bibliothèque, bureau, etc.)','Conventionnel'),
('Garder mon espace de travail à l’ordre.','Conventionnel'),
('. Faire des opérations mathématiques pour préparer des rapports ou faire la tenue de livres','Conventionnel'),
('S’adonner à des activités régulières.','Conventionnel'),
('Classer des lettres, des rapports, des dossiers.','Conventionnel'),
('Recevoir et faire des appels téléphoniques.','Conventionnel'),
('Vérifier des rapports financiers.','Conventionnel'),
('Faire fonctionner toutes sortes de machines de bureau.','Conventionnel'),
('Effectuer des tâches clairement définies.','Conventionnel'),
('Dactylographier ou réviser des lettres ou des rapports.','Conventionnel');


CREATE TABLE question
(

    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    libelle VARCHAR(255),
    indice VARCHAR(100)


)ENGINE=InnoDB;
